version: '2'
services:
  db:
    image: mysql:5.6.34
    ports:
        - "3306:3306"
    volumes:
        - ./tmp/db:/var/lib/mysql/data
    environment:
        - MYSQL_USERNAME=root
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_HOST=mysql
        - MYSQL_DATABASE=dev
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/testing_app
    ports:
      - "3000:3000"
    depends_on:
      - db
